# Generated by Django 4.1.7 on 2023-03-31 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_register', '0009_alter_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
