# Generated by Django 4.1.7 on 2023-04-01 21:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('login_register', '0012_alter_update_pic_profile_pic'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Update_pic',
            new_name='Customer',
        ),
    ]
