# Generated by Django 4.1.7 on 2023-04-02 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_register', '0018_remove_comments_user_comments_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comment',
            field=models.CharField(default=0, max_length=1000),
            preserve_default=False,
        ),
    ]
