# Generated by Django 4.1.7 on 2023-04-02 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_register', '0019_post_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='title',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
