# Generated by Django 4.1.7 on 2023-04-03 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_register', '0020_comments_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='title2',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
