# Generated by Django 4.1.7 on 2023-04-03 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_register', '0021_comments_title2'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_image',
            field=models.ImageField(default=0, upload_to='posts/'),
            preserve_default=False,
        ),
    ]
