# Generated by Django 4.1.7 on 2023-04-03 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_register', '0023_alter_post_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.ImageField(upload_to='posts/'),
        ),
    ]
