# Generated by Django 4.1.7 on 2023-04-06 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
