# Generated by Django 4.1.7 on 2023-04-17 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_alter_myimagemodel_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyImageModel',
        ),
    ]
