# Generated by Django 4.1.7 on 2023-04-18 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_delete_myimagemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default=0, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='image_link',
            field=models.CharField(default=0, max_length=2000),
            preserve_default=False,
        ),
    ]
