# Generated by Django 4.1.7 on 2023-04-19 00:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0013_remove_post_image_remove_post_image_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='post_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='newpost',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='New_post_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
