# Generated by Django 4.1.7 on 2023-04-19 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0014_post_likes_alter_newpost_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newpost',
            name='image',
            field=models.ImageField(default=0, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='newpost',
            name='image_link',
            field=models.CharField(default=0, max_length=2000),
            preserve_default=False,
        ),
    ]
