# Generated by Django 4.1.7 on 2023-04-19 13:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0017_remove_newpost_likes_alter_newcomments_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='newpost',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='New_post_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
